// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ping.proto

package agent;

public final class Ping {
  private Ping() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agent.PingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.agent.AuthResponse auth = 1;</code>
     * @return Whether the auth field is set.
     */
    boolean hasAuth();
    /**
     * <code>.agent.AuthResponse auth = 1;</code>
     * @return The auth.
     */
    agent.Common.AuthResponse getAuth();
    /**
     * <code>.agent.AuthResponse auth = 1;</code>
     */
    agent.Common.AuthResponseOrBuilder getAuthOrBuilder();

    /**
     * <code>.agent.ConnectorType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.agent.ConnectorType type = 2;</code>
     * @return The type.
     */
    agent.Common.ConnectorType getType();
  }
  /**
   * Protobuf type {@code agent.PingRequest}
   */
  public static final class PingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agent.PingRequest)
      PingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingRequest.newBuilder() to construct.
    private PingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingRequest() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PingRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return agent.Ping.internal_static_agent_PingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return agent.Ping.internal_static_agent_PingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              agent.Ping.PingRequest.class, agent.Ping.PingRequest.Builder.class);
    }

    public static final int AUTH_FIELD_NUMBER = 1;
    private agent.Common.AuthResponse auth_;
    /**
     * <code>.agent.AuthResponse auth = 1;</code>
     * @return Whether the auth field is set.
     */
    @java.lang.Override
    public boolean hasAuth() {
      return auth_ != null;
    }
    /**
     * <code>.agent.AuthResponse auth = 1;</code>
     * @return The auth.
     */
    @java.lang.Override
    public agent.Common.AuthResponse getAuth() {
      return auth_ == null ? agent.Common.AuthResponse.getDefaultInstance() : auth_;
    }
    /**
     * <code>.agent.AuthResponse auth = 1;</code>
     */
    @java.lang.Override
    public agent.Common.AuthResponseOrBuilder getAuthOrBuilder() {
      return auth_ == null ? agent.Common.AuthResponse.getDefaultInstance() : auth_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <code>.agent.ConnectorType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.agent.ConnectorType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public agent.Common.ConnectorType getType() {
      agent.Common.ConnectorType result = agent.Common.ConnectorType.forNumber(type_);
      return result == null ? agent.Common.ConnectorType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (auth_ != null) {
        output.writeMessage(1, getAuth());
      }
      if (type_ != agent.Common.ConnectorType.AGENT.getNumber()) {
        output.writeEnum(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (auth_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAuth());
      }
      if (type_ != agent.Common.ConnectorType.AGENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof agent.Ping.PingRequest)) {
        return super.equals(obj);
      }
      agent.Ping.PingRequest other = (agent.Ping.PingRequest) obj;

      if (hasAuth() != other.hasAuth()) return false;
      if (hasAuth()) {
        if (!getAuth()
            .equals(other.getAuth())) return false;
      }
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuth()) {
        hash = (37 * hash) + AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getAuth().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static agent.Ping.PingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agent.Ping.PingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agent.Ping.PingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agent.Ping.PingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agent.Ping.PingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agent.Ping.PingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agent.Ping.PingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agent.Ping.PingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static agent.Ping.PingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static agent.Ping.PingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static agent.Ping.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agent.Ping.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(agent.Ping.PingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agent.PingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agent.PingRequest)
        agent.Ping.PingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agent.Ping.internal_static_agent_PingRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agent.Ping.internal_static_agent_PingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agent.Ping.PingRequest.class, agent.Ping.PingRequest.Builder.class);
      }

      // Construct using agent.Ping.PingRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        auth_ = null;
        if (authBuilder_ != null) {
          authBuilder_.dispose();
          authBuilder_ = null;
        }
        type_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return agent.Ping.internal_static_agent_PingRequest_descriptor;
      }

      @java.lang.Override
      public agent.Ping.PingRequest getDefaultInstanceForType() {
        return agent.Ping.PingRequest.getDefaultInstance();
      }

      @java.lang.Override
      public agent.Ping.PingRequest build() {
        agent.Ping.PingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public agent.Ping.PingRequest buildPartial() {
        agent.Ping.PingRequest result = new agent.Ping.PingRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(agent.Ping.PingRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.auth_ = authBuilder_ == null
              ? auth_
              : authBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof agent.Ping.PingRequest) {
          return mergeFrom((agent.Ping.PingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(agent.Ping.PingRequest other) {
        if (other == agent.Ping.PingRequest.getDefaultInstance()) return this;
        if (other.hasAuth()) {
          mergeAuth(other.getAuth());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAuthFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private agent.Common.AuthResponse auth_;
      private com.google.protobuf.SingleFieldBuilderV3<
          agent.Common.AuthResponse, agent.Common.AuthResponse.Builder, agent.Common.AuthResponseOrBuilder> authBuilder_;
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       * @return Whether the auth field is set.
       */
      public boolean hasAuth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       * @return The auth.
       */
      public agent.Common.AuthResponse getAuth() {
        if (authBuilder_ == null) {
          return auth_ == null ? agent.Common.AuthResponse.getDefaultInstance() : auth_;
        } else {
          return authBuilder_.getMessage();
        }
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      public Builder setAuth(agent.Common.AuthResponse value) {
        if (authBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          auth_ = value;
        } else {
          authBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      public Builder setAuth(
          agent.Common.AuthResponse.Builder builderForValue) {
        if (authBuilder_ == null) {
          auth_ = builderForValue.build();
        } else {
          authBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      public Builder mergeAuth(agent.Common.AuthResponse value) {
        if (authBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            auth_ != null &&
            auth_ != agent.Common.AuthResponse.getDefaultInstance()) {
            getAuthBuilder().mergeFrom(value);
          } else {
            auth_ = value;
          }
        } else {
          authBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      public Builder clearAuth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        auth_ = null;
        if (authBuilder_ != null) {
          authBuilder_.dispose();
          authBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      public agent.Common.AuthResponse.Builder getAuthBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAuthFieldBuilder().getBuilder();
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      public agent.Common.AuthResponseOrBuilder getAuthOrBuilder() {
        if (authBuilder_ != null) {
          return authBuilder_.getMessageOrBuilder();
        } else {
          return auth_ == null ?
              agent.Common.AuthResponse.getDefaultInstance() : auth_;
        }
      }
      /**
       * <code>.agent.AuthResponse auth = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          agent.Common.AuthResponse, agent.Common.AuthResponse.Builder, agent.Common.AuthResponseOrBuilder> 
          getAuthFieldBuilder() {
        if (authBuilder_ == null) {
          authBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              agent.Common.AuthResponse, agent.Common.AuthResponse.Builder, agent.Common.AuthResponseOrBuilder>(
                  getAuth(),
                  getParentForChildren(),
                  isClean());
          auth_ = null;
        }
        return authBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.agent.ConnectorType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.agent.ConnectorType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.agent.ConnectorType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public agent.Common.ConnectorType getType() {
        agent.Common.ConnectorType result = agent.Common.ConnectorType.forNumber(type_);
        return result == null ? agent.Common.ConnectorType.UNRECOGNIZED : result;
      }
      /**
       * <code>.agent.ConnectorType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(agent.Common.ConnectorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.agent.ConnectorType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:agent.PingRequest)
    }

    // @@protoc_insertion_point(class_scope:agent.PingRequest)
    private static final agent.Ping.PingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new agent.Ping.PingRequest();
    }

    public static agent.Ping.PingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingRequest>
        PARSER = new com.google.protobuf.AbstractParser<PingRequest>() {
      @java.lang.Override
      public PingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public agent.Ping.PingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agent.PingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string received = 1;</code>
     * @return The received.
     */
    java.lang.String getReceived();
    /**
     * <code>string received = 1;</code>
     * @return The bytes for received.
     */
    com.google.protobuf.ByteString
        getReceivedBytes();
  }
  /**
   * Protobuf type {@code agent.PingResponse}
   */
  public static final class PingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agent.PingResponse)
      PingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PingResponse.newBuilder() to construct.
    private PingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingResponse() {
      received_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PingResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return agent.Ping.internal_static_agent_PingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return agent.Ping.internal_static_agent_PingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              agent.Ping.PingResponse.class, agent.Ping.PingResponse.Builder.class);
    }

    public static final int RECEIVED_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object received_ = "";
    /**
     * <code>string received = 1;</code>
     * @return The received.
     */
    @java.lang.Override
    public java.lang.String getReceived() {
      java.lang.Object ref = received_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        received_ = s;
        return s;
      }
    }
    /**
     * <code>string received = 1;</code>
     * @return The bytes for received.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceivedBytes() {
      java.lang.Object ref = received_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        received_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(received_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, received_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(received_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, received_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof agent.Ping.PingResponse)) {
        return super.equals(obj);
      }
      agent.Ping.PingResponse other = (agent.Ping.PingResponse) obj;

      if (!getReceived()
          .equals(other.getReceived())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RECEIVED_FIELD_NUMBER;
      hash = (53 * hash) + getReceived().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static agent.Ping.PingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agent.Ping.PingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agent.Ping.PingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agent.Ping.PingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agent.Ping.PingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static agent.Ping.PingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static agent.Ping.PingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agent.Ping.PingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static agent.Ping.PingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static agent.Ping.PingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static agent.Ping.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static agent.Ping.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(agent.Ping.PingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agent.PingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agent.PingResponse)
        agent.Ping.PingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return agent.Ping.internal_static_agent_PingResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return agent.Ping.internal_static_agent_PingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                agent.Ping.PingResponse.class, agent.Ping.PingResponse.Builder.class);
      }

      // Construct using agent.Ping.PingResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        received_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return agent.Ping.internal_static_agent_PingResponse_descriptor;
      }

      @java.lang.Override
      public agent.Ping.PingResponse getDefaultInstanceForType() {
        return agent.Ping.PingResponse.getDefaultInstance();
      }

      @java.lang.Override
      public agent.Ping.PingResponse build() {
        agent.Ping.PingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public agent.Ping.PingResponse buildPartial() {
        agent.Ping.PingResponse result = new agent.Ping.PingResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(agent.Ping.PingResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.received_ = received_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof agent.Ping.PingResponse) {
          return mergeFrom((agent.Ping.PingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(agent.Ping.PingResponse other) {
        if (other == agent.Ping.PingResponse.getDefaultInstance()) return this;
        if (!other.getReceived().isEmpty()) {
          received_ = other.received_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                received_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object received_ = "";
      /**
       * <code>string received = 1;</code>
       * @return The received.
       */
      public java.lang.String getReceived() {
        java.lang.Object ref = received_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          received_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string received = 1;</code>
       * @return The bytes for received.
       */
      public com.google.protobuf.ByteString
          getReceivedBytes() {
        java.lang.Object ref = received_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          received_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string received = 1;</code>
       * @param value The received to set.
       * @return This builder for chaining.
       */
      public Builder setReceived(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        received_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string received = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceived() {
        received_ = getDefaultInstance().getReceived();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string received = 1;</code>
       * @param value The bytes for received to set.
       * @return This builder for chaining.
       */
      public Builder setReceivedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        received_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:agent.PingResponse)
    }

    // @@protoc_insertion_point(class_scope:agent.PingResponse)
    private static final agent.Ping.PingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new agent.Ping.PingResponse();
    }

    public static agent.Ping.PingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PingResponse>
        PARSER = new com.google.protobuf.AbstractParser<PingResponse>() {
      @java.lang.Override
      public PingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public agent.Ping.PingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_PingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_PingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_PingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_PingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nping.proto\022\005agent\032\014common.proto\"T\n\013Pin" +
      "gRequest\022!\n\004auth\030\001 \001(\0132\023.agent.AuthRespo" +
      "nse\022\"\n\004type\030\002 \001(\0162\024.agent.ConnectorType\"" +
      " \n\014PingResponse\022\020\n\010received\030\001 \001(\t2D\n\013Pin" +
      "gService\0225\n\004Ping\022\022.agent.PingRequest\032\023.a" +
      "gent.PingResponse\"\000(\0010\001B$Z\"github.com/ut" +
      "mstack/UTMStack/agentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          agent.Common.getDescriptor(),
        });
    internal_static_agent_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agent_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_PingRequest_descriptor,
        new java.lang.String[] { "Auth", "Type", });
    internal_static_agent_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agent_PingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_PingResponse_descriptor,
        new java.lang.String[] { "Received", });
    agent.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
